// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/sirupsen/logrus"
	"template/internal/config"
	"template/internal/repo"
	"template/internal/server"
	"template/internal/biz"
	"template/pkg/manager"
)

import (
	_ "gorm.io/driver/mysql"
)

// Injectors from wire.go:

func initApp(logger *logrus.Logger, db *gorm.DB, info config.AppInfo) (*manager.App, error) {
	userRepo := repo.NewUserRepo(db, logger)
	userService := biz.NewUserService(userRepo)
	managerServer := server.NewHTTPServer(logger, info, userService)
	app := newApp(logger, managerServer, info)
	return app, nil
}
